---
- name: Setup Vprofile Bastion Host
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup Variable
      include_vars: vars/vpc_setup

    - name: Import VPC setup Variable
      include_vars: vars/output_vars

    - name: Create a new EC2 key pair, returns generated private key
      amazon.aws.ec2_key:
        name: bastion-key
        state: "{{state}}"
        region: "{{ region }}"
      register: bastion_key

    - name: Save private key to PEM file
      ansible.builtin.copy:
        content: "{{ bastion_key.key.private_key }}"
        dest: "./bastion-key.pem"
        mode: '0600'
      when: bastion_key.changed

    - name: Create Bastion Host security group
      amazon.aws.ec2_security_group:
        name: Bastion-SG
        description: Allow port 22 from everywhere and all port within sg
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ MYIP }}"
        tags:
          Name: bastion-sg
          Project: vprofile
      register: bastion_sg

    - name: Launch Bastion Host EC2 instance
      amazon.aws.ec2_instance:
        name: bastion-host
        region: "{{ region }}"
        key_name: bastion-key
        instance_type: "{{ instance_type }}"
        image_id: "{{ bastion_ami }}"
        wait: true
        wait_timeout: 300
        vpc_subnet_id: "{{ pub_sub1_id }}"
        security_groups:
          - "{{ bastion_sg.group_id }}"
        tags:
          Name: bastion-host
          Role: jumpbox
          Project: vprofile
      register: bastion_instance


    - name: Show Bastion Host Public IP
      debug:
        var: "Bastion Public IP: {{ bastion_instance.instances[0].public_ip_address }}"


    - name: Insert/Update "bastion_sg" in vars/output_vars
      ansible.builtin.blockinfile:
        path: vars/output_vars
        backup: yes
        block: |
          bastion_sg_id: {{bastion_sg.group_id}}






