---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup

    - name: Create vprofile VPC
      amazon.aws.ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpc_Cidr }}"
        region: "{{ region }}"
        state: "{{state}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        tags:
          Project: vprofile
      register: vpc

    - name: Create public subnet for zone1
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ PubSub1Cidr }}"
        az: "{{ zone1 }}"
        map_public: true
        state: "{{state}}"
        region: "{{ region }}"
        tags:
          Name: public-subnet1
          Project: vprofile
      register: public_subnet1

    - name: Create public subnet for zone2
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ PubSub2Cidr }}"
        az: "{{ zone2 }}"
        map_public: true
        state: present
        region: "{{ region }}"
        tags:
          Name: public-subnet2
          Project: vprofile
      register: public_subnet2

    - name: Create public subnet for zone3
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ PubSub3Cidr }}"
        az: "{{ zone3 }}"
        map_public: true
        state: "{{state}}"
        region: "{{ region }}"
        tags:
          Name: public-subnet3
          Project: vprofile
      register: public_subnet3

    - name: Create private subnet for zone1
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ PrivSub1Cidr }}"
        az: "{{ zone1 }}"
        state: "{{state}}"
        region: "{{ region }}"
        tags:
          Name: private-subnet1
          Project: vprofile
      register: private_subnet1

    - name: Create private subnet for zone2
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ PrivSub2Cidr }}"
        az: "{{ zone2 }}"
        state: "{{state}}"
        region: "{{ region }}"
        tags:
          Name: private-subnet2
          Project: vprofile
      register: private_subnet2

    - name: Create private subnet for zone3
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ PrivSub3Cidr }}"
        az: "{{ zone3 }}"
        state: "{{state}}"
        region: "{{ region }}"
        tags:
          Name: private-subnet3
          Project: vprofile
      register: private_subnet3

    - name: Create Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        state: "{{state}}"
        tags:
          Name: vprofile-igw
      register: igw

    - name: Set up public subnet route table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        tags:
          Name: vprofile-public-rt
          Project: vprofile
        subnets:
          - "{{ public_subnet1.subnet.id }}"
          - "{{ public_subnet2.subnet.id }}"
          - "{{ public_subnet3.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
      register: public_route_table

    - name: Create NAT Gateway in public subnet1
      amazon.aws.ec2_vpc_nat_gateway:
        subnet_id: "{{ public_subnet1.subnet.id }}"
        region: "{{ region }}"
        state: present
        wait: true
        if_exist_do_not_create: true
        tags:
          Name: vprofile-natgw
      register: nat_gateway

    - name: Set up private subnet route table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        tags:
          Name: vprofile-private-rt
          Project: vprofile
        subnets:
          - "{{ private_subnet1.subnet.id }}"
          - "{{ private_subnet2.subnet.id }}"
          - "{{ private_subnet3.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            nat_gateway_id: "{{ nat_gateway.nat_gateway_id }}"
      register: private_route_table


