---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup

    - name: Create vprofile VPC
      amazon.aws.ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpc_Cidr }}"
        region: "{{ region }}"
        state: "{{state}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        tags:
          Project: vprofile
      register: vpc

    - name: Create public subnet for zone1
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ PubSub1Cidr }}"
        az: "{{ zone1 }}"
        map_public: true
        state: present
        region: "{{ region }}"
        tags:
          Name: public-subnet1
          Project: vprofile
      register: public_subnet1

    - name: Create public subnet for zone2
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ PubSub2Cidr }}"
        az: "{{ zone2 }}"
        map_public: true
        state: present
        region: "{{ region }}"
        tags:
          Name: public-subnet2
          Project: vprofile
      register: public_subnet2

    - name: Create public subnet for zone3
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ PubSub3Cidr }}"
        az: "{{ zone3 }}"
        map_public: true
        state: present
        region: "{{ region }}"
        tags:
          Name: public-subnet3
          Project: vprofile
      register: public_subnet3

    - name: Create private subnet for zone1
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ PrivSub1Cidr }}"
        az: "{{ zone1 }}"
        map_public: true
        state: present
        region: "{{ region }}"
        tags:
          Name: private-subnet1
          Project: vprofile
      register: private_subnet1

    - name: Create private subnet for zone2
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ PrivSub2Cidr }}"
        az: "{{ zone2 }}"
        map_public: true
        state: present
        region: "{{ region }}"
        tags:
          Name: private-subnet2
          Project: vprofile
      register: private_subnet2

    - name: Create private subnet for zone3
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ PrivSub3Cidr }}"
        az: "{{ zone3 }}"
        map_public: true
        state: present
        region: "{{ region }}"
        tags:
          Name: private-subnet3
          Project: vprofile
      register: private_subnet3