---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup

    - name: Create vprofile VPC
      amazon.aws.ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpc_Cidr }}"
        region: "{{ region }}"
        state: "{{state}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        tags:
          Project: vprofile
      register: vpc

    - name: Create public subnet for zone1
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ PubSub1Cidr }}"
        az: "{{ zone1 }}"
        map_public: true
        state: present
        region: "{{ region }}"
        tags:
          Name: public-subnet1
          Project: vprofile
      register: public_subnet1