---
- name: setup Vprofile Stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup Variable
      include_vars: vars/output_vars

    - name: Import Vprofile setup variable
      include_vars: vars/vprostack_setup

    - name: Create a new EC2 key pair, returns generated private key
      amazon.aws.ec2_key:
        name: vprokey
        state: "{{state}}"
        region: "{{ region }}"
      register: vprokey

    - name: Save private key to PEM file
      ansible.builtin.copy:
        content: "{{ vprokey.key.private_key }}"
        dest: "./loginkey.pem"
        mode: '0600'
      when: vprokey.changed

    - name: Create load balancer security group
      amazon.aws.ec2_security_group:
        name: vproELB-SG
        description: Allow port 80 from everywhere and all port within sg
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
        tags:
          Name: vproELB-SG
          Project: vprofile
      register: vproELB_SG

    - name: Create Vprofile stack security group
      amazon.aws.ec2_security_group:
        name: vprostack-SG
        description: Allow port 80 from everywhere and all port within sg
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{vproELB_SG.group_id}}"

          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{bastion_sg_id}}"
        tags:
          Name: vprostack-SG
          Project: vprofile
      register: vprostack_SG